# Default plugin configuration!
worlds:
    # World name on this line
    DMArena:
        spawns:
            # Name the location what you'd like, for organization
            a:
            # X coordinate
                x: 669.50
            # Y coordinate
                y: 8.50
            # Z coordinate
                z: -293.50
            b:
                x: 619.50
                y: 8.50
                z: -213.50
            c:
                x: 569.50
                y: 8.50
                z: -293.50
            d:
                x: 619.50
                y: 8.50
                z: -313.50