# Default plugin configuration!
worlds:
    # World name on this line
    DMArena:
        spawns:
            # Name the location what you'd like, for organization
            a:
            # X coordinate
            - 669.50
            # Y coordinate
            - 8.50
            # Z coordinate
            - -293.50
            b:
            - 619.50
            - 8.50
            - -213.50
            c:
            - 569.50
            - 8.50
            - -293.50
            d:
            - 619.50
            - 8.50
            - -313.50