name: OtisArena
main: me.otisdiver.otisarena.OtisArena
version: 0.2.0
author: Brian Schultz
commands:
    endgame:
        description: End a currently running game.
        permission: gameadmin
        usage: /endgame <restart? yes/no>
