name: OtisArena
main: me.otisdiver.otisarena.OtisArena
version: 1.0.0
author: Brian Schultz
commands:
    game:
        description: Manage the game.
        permission: gameadmin
        usage: /game <restart/stop>
